#!/bin/bash

make_light='/home/kacper/Documents/cv/make_light'

./make_all -t " " "$make_light" "./start/" "./" "pl"

cp pl.html index.html

cp ./start/pl.md ./cv.md

pandoc cv.md -o insidecv.tex
cat precv.tex insidecv.tex postcv.tex > KacperTopolnickiCV.tex

pandoc cv.md -o cv.pdf



